# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z2x7bhfuok29074HAS89YMUjqtv9iiDM
"""

!pip install gradio



from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("train.csv")
df.head()

"""# New section"""

# ================================
#  GRADIO HOUSE PRICE PREDICTOR
#  (Variable outputs without model)
# ================================
import os
import pandas as pd
import numpy as np
import random

# 1) Install gradio if missing
try:
    import gradio as gr
except ImportError:
    print("Installing Gradio...")
    !pip install -q gradio==5.50.0
    import gradio as gr

print("Gradio version:", gr.__version__)

# ------------------------------
# 2) Locate train.csv
# ------------------------------
TRAIN_CSV_PATH = "train.csv" if os.path.exists("train.csv") else None

if TRAIN_CSV_PATH is None:
    from google.colab import files
    print("Please upload train.csv now.")
    uploaded = files.upload()
    for name in uploaded:
        if name.endswith(".csv"):
            TRAIN_CSV_PATH = name

# ------------------------------
# 3) Load train.csv
# ------------------------------
df_train = pd.read_csv(TRAIN_CSV_PATH)
print("Loaded train.csv with shape", df_train.shape)

# Infer features
num_features = []
cat_features = []

for col in df_train.columns:
    if col == 'SalePrice':
        continue
    if pd.api.types.is_numeric_dtype(df_train[col]):
        num_features.append(col)
    else:
        cat_features.append(col)

print(f"Inferred {len(num_features)} numerical features and {len(cat_features)} categorical features.")

# ------------------------------
# 4) Prediction function (Option 1)
# ------------------------------
def predict_price(*args):
    # Base price
    base_price = 50000
    price = base_price

    # Add effect of numeric inputs
    for i, val in enumerate(args[:len(num_features)]):
        price += val * random.uniform(100, 300)

    # Add random noise
    price += random.randint(-20000, 20000)

    return f"Predicted House Price: ${price:,.2f}"

# ------------------------------
# 5) Build Gradio UI
# ------------------------------
inputs = []

# Numeric sliders
for feature in num_features:
    if feature in df_train.columns:
        min_val = float(df_train[feature].min())
        max_val = float(df_train[feature].max())
    else:
        min_val, max_val = 0, 1000
    inputs.append(gr.Slider(minimum=min_val, maximum=max_val, step=1, label=feature))

# Categorical dropdowns
for feature in cat_features:
    if feature in df_train.columns:
        choices = sorted(df_train[feature].dropna().unique().tolist())
        inputs.append(gr.Dropdown(choices=choices, label=feature))
    else:
        inputs.append(gr.Textbox(label=feature))

output = gr.Textbox(label="Predicted House Price")

# ------------------------------
# 6) Launch Gradio App
# ------------------------------
print("Launching Gradio interface...")
gr.Interface(
    fn=predict_price,
    inputs=inputs,
    outputs=output,
    title="🏠 House Price Predictor (Simulated Outputs)"
).launch(share=True)